// // <auto-generated/>
// using System;
// using Microsoft.SemanticKernel;
//
// namespace Skgen.Sample;
//
// public static partial class KernelExtensionMethods
// {
//     
//     public static async Task<FunctionResult> Publication(this Kernel kernel)
//     {
//         var arguments = new KernelArguments();
//     
//         var answer = await kernel.InvokeAsync("Publication", "functionName", arguments, CancellationToken.None);
//         return answer;
//     }
//     
// //    public static partial class Program
// //    {
// //        static partial void HelloFrom(string name) =>
// //            Console.WriteLine($"Generator says: Hi System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.AdditionalText] from '{name}'");
// //    }
// }